services:
  elasticsearch:
    build: . # 현재 폴더의 Docker Image 를 읽어서 Custom Image 생성
    container_name: kumarketto_es
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false # 개발용으로 보안 비활성화
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ports:
      - "9084:9200" # 외부 9200 포트를 컨테이너 9200 포트와 연결
      - "9453:9300" # 다중 클러스터 구성 시 필요(다른 Elasticsearch node 를 위함 -> 현재는 single node)
    networks:
      - es-net

  kibana:
    image: kibana:8.8.2
    container_name: kumarketto_kibana
    ports:
      - "5601:5601" # kibana 기본 접속 포트
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200 # 접속해야 할 Elasticsearch 주소
    depends_on:
      - elasticsearch
    networks:
      - es-net

networks:
  es-net:
    driver: bridge
